### PR TITLE
Add test cases and fix and method

### PR DESCRIPTION
**Pull request by pwener**
Hi, before continue I have a question, we can put all test together?

### CODE REVIEW

**Comment by MikeMcl** [comment]
@pwener 

The results and timings will not be correct if more than one `Test` call is used in a file. 

I also think you should add more test cases!

*bitwise.js*
```js
if (typeof Test === 'undefined') require('../tester');

Test('bitwise', function () {
    var bitwiseMethods = {
      '<<': 'bitShiftLeft',
      '>>': 'bitShiftRight',
      '&&': 'and'
    };

    function t(a, method, b, expected) {
        Test.areEqual(String(expected), String(new BigNumber(a)[bitwiseMethods[method]](b)));
    }
    
    BigNumber.config({
        DECIMAL_PLACES: 20,
        ROUNDING_MODE: 4,
        RANGE: 1E9,
        EXPONENTIAL_AT: [-7, 21]
    });

    t(5, '<<', 1, 10);
    t(1, '<<', 1, 2);
    t(1, '<<', 1, 2);

    t(5, '>>', 1, 2);
    t(1, '>>', 1, 0);

    t(0, '&&', 0, 0);
    t(1, '&&', 1, 1);
    t(82, '&&', 272, 16);
    t(9, '&&', 57, 9);
}); 
```

**Comment by MikeMcl** [comment]
@pwener 

Looks good.

I notice you haven't touched or tested the `not` method. I think its last line should be changed to  `return not.plus(dec);`.

For all the methods, the question is: is it right to restore the decimal part (i.e. fraction digits) of the number after the bitwise operation on the integer part? Personally, I would lean towards discarding it.

In fact, I would throw if a bitwise operation is attempted on a BigNumber with fraction digits.

```js
if (!this.isInteger()) {
  throw Error
    (bignumberError + 'Not an integer: ' + valueOf(this));
}
```

That would also have the advantage of removing the need for code such as

```js
var dec = this.modulo(1);
var int = this.integerValue();
```

which was inefficient anyway because the `modulo` operation involves an expensive division operation, as well as a subtraction and a multiplication. A single subtraction would have been preferred:

```js
//  `int` is a reserved word in ES3, so is not used here.
var intPart = this.integerValue();
var fracPart = this.minus(intPart);
```

What do you think about that? Would you prefer to:
 * keep the current behaviour, or
 * just ignore the decimal part and don't include it in the result, or
 * throw if an operation is attemped on a non-integer BigNumber?

**Comment by Vap0r1ze** [comment]
I think it would be best to mimic JS behaviour and ignore the decimal part, not including it in the result

**Comment by MikeMcl** [comment]
After you putting it like that, I agree.

**Comment by pwener** [comment]
I was thinking that we can create an private method to reuse in and(&), or(|) and xor(^), their implementation are  very similar. What do you think?

**Comment by Vap0r1ze** [comment]
> I was thinking that we can create an private method to reuse in and(&), or(|) and xor(^), their implementation are very similar. What do you think?

I believe this is a question for @MikeMcl, just bumping

**Comment by pwener** [comment]
For both, because this is a change that maybe you want to do personally. 😄

**Comment by Vap0r1ze** [comment]
I don't have the time to at the moment, I wouldn't mind if you implemented it yourself

**Comment by pwener** [comment]
I think it is done, @MikeMcl @Vap0r1ze any point here?

**Comment by pwener** [comment]
@Vap0r1ze

**Comment by MikeMcl** [comment]
@pwener

Looks great. I'll do some more testing and I'll take a careful look at the PR presently.

**Pull request merged**
